# Generated by Django 3.2 on 2022-04-01 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220401_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 4, 1, 7, 38, 4, 877594, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
