# Generated by Django 3.2 on 2022-06-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220624_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
    ]
